### ISSUE TITLE
<c-p> in telescope works with huge delay (possible issue with <c-p>p).

### ISSUE THREAD

**Issue by Inom-Turdikulov** [jghauser/papis.nvim#22]
Just for someone who can have same issue.
I use `<c-p>` key to navigate to previous item in telescope.
If papis `enable_keymaps` is `true`, I have very strange behaviour. Nvim insert some escape sequence (or something like this) and selecting previous item is processing with huge delay.

I have this issue in `xtrem` and `kitty`.  

https://github.com/jghauser/papis.nvim/assets/3938577/e6728922-43b7-416a-9bc1-aef056f6c3dd

**Comment by jghauser** [comment]
Thanks for your issue report! I'm pretty sure it's because `<c-p>[some_letter]` is used as a shortcut in insert mode for various things by papis.nvim. This means that when you press just `<c-p>`, nvim is waiting to see with what additional character you will complete the shortcut and only after some time will execute the command mapped to `<c-p>`. This isn't great given that `<c-p>` is used by default in nvim to select the next item in various lists if I'm not mistaken. I've remapped this to `<tab>` on my machine and therefore didn't notice the clash.

I'll think about how to best deal with this. `<c-p>` does seem like the natural insert mode equivalent of the standard `<leader-p>`. Maybe I can figure out some way to only use the mapping in standard insert mode (and not in telescope windows or when using some autocomplete feature). Or, do you maybe have any ideas on how to best deal with this?

**Comment by Inom-Turdikulov** [comment]
> Thanks for your issue report! I'm pretty sure it's because `<c-p>[some_letter]` is used as a shortcut in insert mode for various things by papis.nvim. This means that when you press just `<c-p>`, nvim is waiting to see with what additional character you will complete the shortcut and only after some time will execute the command mapped to `<c-p>`. This isn't great given that `<c-p>` is used by default in nvim to select the next item in various lists if I'm not mistaken. I've remapped this to `<tab>` on my machine and therefore didn't notice the clash.
> 
> I'll think about how to best deal with this. `<c-p>` does seem like the natural insert mode equivalent of the standard `<leader-p>`. Maybe I can figure out some way to only use the mapping in standard insert mode (and not in telescope windows or when using some autocomplete feature). Or, do you maybe have any ideas on how to best deal with this?

Honestly I have no idea how do it properly. On my side I just disabled built-in keymaps (thank you for this option) and I use only custom keymaps in normal mode right now. Maybe possible to detect "telescope insert mode" and disable mapping for it.

**Comment by jghauser** [comment]
Ok, I'll see what I come up with and get back to you! :)

**Comment by jghauser** [comment]
Ok, this took a while :sweat:. I've made keybinds local to buffers (so they don't mess with Telescope). I've also had to change some other keybinds because <c-n> (new note) still clashed. You might want to re-enable the default keybinds, though I guess you've probably found a setup that works for you by now :). Thanks again for the report!
