### ISSUE TITLE
Setup impossible

### ISSUE THREAD

**Issue by albedorsch** [jghauser/papis.nvim#30]
My config is here
https://gitlab.gnugen.ch/dorsch/nvim_config

Running
:Telescope papis
in nvim gives the following error
                                                                        
Error executing Lua callback: ...acker/opt/papis.nvim/lua/telescope/_ext
ensions/papis.lua:49: attempt to index field 'search' (a nil value)
stack traceback:
        ...acker/opt/papis.nvim/lua/telescope/_extensions/papis.lua:49: 
in function 'entry_maker'
        ...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: 
in function 'new_table'
        ...acker/opt/papis.nvim/lua/telescope/_extensions/papis.lua:46: 
in function <...acker/opt/papis.nvim/lua/telescope/_extensions/papis.lua
:38>
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:199:
 in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:259:
 in function 'load_command'
        ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:108:
 in function <...te/pack/packer/start/telescope.nvim/plugin/telescope.lu
a:107>
Press ENTER or type command to continue

**Comment by jghauser** [comment]
Hi! Thanks for the issue report. I see from your config that you copied over all of the defaults. Maybe try with a more minimal setup, just adding what's noted as required in the readme. Note that Papis only starts when opening a file that matches what's defined in `init_filenames`. Try running `PapisStart` first otherwise, which will initialise Papis and setup the database (the error suggests that this hasn't happened yet). As a final resort, there's also `PapisReInitData` to force a reinitialisation. Let me know if any/none of this helps!

**Comment by jghauser** [comment]
Doing a little spring cleaning and closing this issue as it seemed to have been something with your configuration. If the problem still exists, do let me know! :)
